apiVersion: v1
kind: Secret
metadata:
  name: puppetdb-cnpg-superuser-secret
type: kubernetes.io/basic-auth
data:
  username: cG9zdGdyZXM= # postgres
  password: {{ .Values.cnpg.superuserpassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: puppetdb-cnpg-user-secret
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.cnpg.username | b64enc | quote }}
  password: {{ .Values.cnpg.password | b64enc | quote }}
