apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetserver
spec:
  selector:
    matchLabels:
      app: puppetserver
  replicas: 1
  template:
    metadata:
      labels:
        app: puppetserver
    spec:
      terminationGracePeriodSeconds: 180

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      hostname: {{ .Values.server.hostname | quote }}

      containers:

      - name: server
        image: {{ .Values.server.image | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8140

        env:
        - name: HOSTNAME
          value: {{ .Values.server.hostname | quote }}

        securityContext:
          privileged: false
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        resources:
          limits:
            cpu: {{ .Values.instance.maxcpu }}
            memory: {{ .Values.instance.maxram }}
          requests:
            cpu: {{ .Values.instance.mincpu }}
            memory: {{ .Values.instance.minram }}

        volumeMounts:
        - name: puppet-cert-ca
          mountPath: /opt/puppet-cert/ca
          readOnly: true
        - name: puppet-cert-signed
          mountPath: /opt/puppet-cert/signed
          readOnly: true

      serviceAccountName: puppet-cert-saver-sa

      volumes:
      - name: puppet-cert-ca
        secret:
          secretName: puppet-cert-ca-secret
      - name: puppet-cert-signed
        secret:
          secretName: puppet-cert-signed-secret
