apiVersion: v1
kind: Service
metadata:
  name: puppetserver
  annotations:
    helm.sh/hook: pre-install
spec:
  selector:
    app: puppetserver
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8140
    targetPort: 8140
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: puppetserver
#  annotations:
#    helm.sh/hook: pre-install
#    helm.sh/hook-delete-policy: hook-succeeded
#spec:
#  selector:
#    app: puppet-hook-init-certs
#  type: ClusterIP
#  ports:
#  - protocol: TCP
#    port: 8140
#    targetPort: 8140
#