apiVersion: v1
kind: Secret
metadata:
  name: puppetserver-cert-ca-secret
{{ if .Values.instance.keepCerts }}
  annotations:
    "helm.sh/resource-policy": keep
{{ end }}
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: puppetserver-cert-signed-secret
{{ if .Values.instance.keepCerts }}
  annotations:
    "helm.sh/resource-policy": keep
{{ end }}
type: Opaque
data: {}
