apiVersion: v1
kind: Service
metadata:
  name: puppetserver-loadbalancer
  annotations:
    metallb.universe.tf/address-pool: privmuni
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.server.url }}
spec:
  type: LoadBalancer
  ports:
  - port: 8140
    targetPort: 8140
    protocol: TCP
  selector:
    app: puppetserver # Service name
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Local
