apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: puppet-cert-saver-role
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: puppet-cert-saver-sa
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: puppet-cert-saver-rb
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: puppet-cert-saver-role
subjects:
- kind: ServiceAccount
  name: puppet-cert-saver-sa
