apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetserver
spec:
  selector:
    matchLabels:
      app: puppetserver
  replicas: 1
  template:
    metadata:
      labels:
        app: puppetserver
    spec:
      terminationGracePeriodSeconds: 180

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      hostname: {{ .Values.server.hostname | quote }}

      containers:

      - name: server
        image: {{ .Values.server.image | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8140

        command: ["/docker-entrypoint.sh"]

        env:
        - name: HOSTNAME
          value: {{ .Values.server.hostname | quote }}
        - name: NAMESPACE
          value: {{ .Values.namespace | quote }}
        - name: HOSTNAME_FULL_PUPPETSERVER
          value: "{{ .Values.server.hostname }}.{{ .Values.namespace }}.svc.cluster.local"
        - name: HOSTNAME_FULL_PUPPETDB
          value: "{{ .Values.db.hostname }}.{{ .Values.namespace }}.svc.cluster.local"

        securityContext:
          privileged: false
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /status/v1/services
            port: 8140
          initialDelaySeconds: 10
          periodSeconds: 10

        resources:
          limits:
            cpu: {{ .Values.server.resources.maxcpu }}
            memory: {{ .Values.server.resources.maxram }}
          requests:
            cpu: {{ .Values.server.resources.mincpu }}
            memory: {{ .Values.server.resources.minram }}

        volumeMounts:
        - name: ps-cert-ca
          mountPath: /opt/puppet-cert-mount/ca
          readOnly: true
        - name: ps-cert-signed
          mountPath: /opt/puppet-cert-mount/signed
          readOnly: true

      serviceAccountName: puppet-cert-saver-sa

      volumes:
      - name: ps-cert-ca
        secret:
          secretName: puppetserver-cert-ca-secret
      - name: ps-cert-signed
        secret:
          secretName: puppetserver-cert-signed-secret
