apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetdb
spec:
  selector:
    matchLabels:
      app: puppetdb
  replicas: 1
  template:
    metadata:
      labels:
        app: puppetdb
    spec:
      terminationGracePeriodSeconds: 180

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      hostname: {{ .Values.db.hostname | quote }}

      containers:

      - name: server
        image: {{ .Values.db.image | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

        env:
        - name: HOSTNAME
          value: {{ .Values.db.hostname | quote }}
        - name: HOSTNAME_FULL
          value: "{{ .Values.db.hostname }}.{{ .Values.namespace }}.svc.cluster.local"
        - name: NAMESPACE
          value: {{ .Values.namespace | quote }}
        - name: PGHOST
          value: "puppetdb-cnpg-rw"
        - name: PGDATABASE
          value: {{ .Values.cnpg.database | quote }}
        - name: PGUSER
          value: {{ .Values.cnpg.username | quote }}
        - name: PGPASSWORD
          value: {{ .Values.cnpg.password | quote }}

        securityContext:
          privileged: false
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

# Even though the build-in HTTPS support for readiness probe skip the certificate verification,
# the probe fails because PuppetDB uses mutual TLS. This is the reason why the `curl` is used.
        readinessProbe:
          exec:
            command:
            - /usr/bin/curl
            - --insecure
            - --cacert
            - /etc/puppetlabs/puppet/ssl/certs/ca.pem
            - --cert
            - /etc/puppetlabs/puppet/ssl/certs/{{ .Values.db.hostname }}.{{ .Values.namespace }}.svc.cluster.local.pem
            - --key
            - /etc/puppetlabs/puppet/ssl/private_keys/{{ .Values.db.hostname }}.{{ .Values.namespace }}.svc.cluster.local.pem
            - https://localhost:8081/status/v1/services
          initialDelaySeconds: 10
          periodSeconds: 10

        resources:
          limits:
            cpu: {{ .Values.db.resources.maxcpu }}
            memory: {{ .Values.db.resources.maxram }}
          requests:
            cpu: {{ .Values.db.resources.mincpu }}
            memory: {{ .Values.db.resources.minram }}

        volumeMounts:
        - name: pd-cert-private
          mountPath: /opt/puppet-cert/private
          readOnly: true

      serviceAccountName: puppet-cert-saver-sa

      volumes:
      - name: pd-cert-private
        secret:
          secretName: puppetdb-cert-private-secret
