{{ if .Values.instance.generateSecrets }}
apiVersion: batch/v1
kind: Job
metadata:
  name: puppetserver
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: puppetserver
    spec:

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      hostname: {{ .Values.server.hostname | quote }}
      restartPolicy: OnFailure

      containers:
      - name: server
        image: {{ .Values.server.image | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8140

        command: ["/docker-entrypoint-hook.sh"]

        env:
        - name: HOSTNAME
          value: {{ .Values.server.hostname | quote }}
        - name: NAMESPACE
          value: {{ .Values.namespace | quote }}
        - name: HOSTNAME_FULL_PUPPETSERVER
          value: "{{ .Values.server.hostname }}.{{ .Values.namespace }}.svc.cluster.local"
        - name: HOSTNAME_FULL_PUPPETDB
          value: "{{ .Values.db.hostname }}.{{ .Values.namespace }}.svc.cluster.local"
        - name: HOSTNAME_FULL_PUPPETBOARD
          value: "{{ .Values.board.hostname }}.{{ .Values.namespace }}.svc.cluster.local"

        securityContext:
          privileged: false
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL

        resources:
          limits:
            cpu: {{ .Values.server.resources.maxcpu }}
            memory: {{ .Values.server.resources.maxram }}
          requests:
            cpu: {{ .Values.server.resources.mincpu }}
            memory: {{ .Values.server.resources.minram }}

      serviceAccountName: puppet-cert-saver-sa
{{ end }}