apiVersion: v1
kind: Service
metadata:
  name: puppetserver
{{ if .Values.instance.generateSecrets }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
{{ end }}
spec:
  selector:
    app: puppetserver
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8140
    targetPort: 8140
