apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: puppet-cert-saver-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: puppet-cert-saver-sa
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: puppet-cert-saver-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: puppet-cert-saver-role
subjects:
- kind: ServiceAccount
  name: puppet-cert-saver-sa
