apiVersion: v1
kind: Service
metadata:
  name: puppetserver-svc
spec:
  selector:
    app: puppetserver
  type: ClusterIP
  ports:
  - name: puppetserver
    protocol: TCP
    port: 8140
    targetPort: 8410
