instance:
  # Allows to start `pre-install` hook to generate and save (or OVERWRITE!} the Puppet certificates to Kubernetes
  # Secrets.
  # ---
  # Because the Secrets storing the certificates and keys for the PuppetServer CA are not assigned to this Helm chart,
  # they won't be removed after uninstalling this Helm chart. If there are any residual Secrets related with previous
  # installation of this chart, they will overwriten if this option is allowed. However first installation requires to
  # enable it.
  generateSecrets: false

namespace: ""

# Puppet Server application
server:
  image: ""
  hostname: "puppetserver"
  url: ""

  gitRepo: ""
  # Repository with configs (SSH protocol only! - e.g.: "git@github.com:myname/myproject.git")

  resources:
    maxcpu: "2"
    maxram: "5Gi"
    mincpu: "200m"
    minram: "3Gi"

  # r10k application in the same pod
  r10k:
    image: ""
    resources:
      maxcpu: "2"
      maxram: "1Gi"
      mincpu: "100m"
      minram: "500Mi"

# Puppet DB application
db:
  image: ""
  hostname: "puppetdb"

  resources:
    maxcpu: "2"
    maxram: "2Gi"
    mincpu: "200m"
    minram: "1Gi"

  postgres:
    database: ""
    username: ""
    password: ""

# Puppet Board application (https://github.com/voxpupuli/puppetboard)
board:
  image: ""
  hostname: "puppetboard"
  url: ""

  resources:
    maxcpu: "2"
    maxram: "2Gi"
    mincpu: "200m"
    minram: "500Mi"

  oauth2Proxy:
    image: "quay.io/oauth2-proxy/oauth2-proxy:latest"
    hostname: "oauth2-proxy"
    oidcUrl: ""

    clientId: ""
    clientSecret: ""
    # Generate using the following command:
    # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
    cookieSecret: ""

    resources:
      maxcpu: "2"
      maxram: "1Gi"
      mincpu: "100m"
      minram: "500Mi"