instance:
  # Allows to start `pre-install` hook to generate and save (or OVERWRITE!} the Puppet certificates to Kubernetes
  # Secrets.
  # ---
  # Because the Secrets storing the certificates and keys for the PuppetServer CA are not assigned to this Helm chart,
  # they won't be removed after uninstalling this Helm chart. If there are any residual Secrets related with previous
  # installation of this chart, they will overwriten if this option is allowed. However first installation requires to
  # enable it.
  generateSecrets: false

namespace: ""

# Puppet Server application
server:
  image: ""
  hostname: "puppetserver"
  url: ""

  # Repository with configs
  gitRepo: ""

  resources:
    maxcpu: "2"
    maxram: "5Gi"
    mincpu: "200m"
    minram: "3Gi"

  # r10k application in the same pod
  r10k:
    image: ""
    resources:
      maxcpu: "2"
      maxram: "1Gi"
      mincpu: "100m"
      minram: "500Mi"

# Puppet DB application
db:
  image: ""
  hostname: "puppetdb"

  resources:
    maxcpu: "2"
    maxram: "2Gi"
    mincpu: "200m"
    minram: "1Gi"

  postgres:
    database: ""
    username: ""
    password: ""

# Puppet Board application (https://github.com/voxpupuli/puppetboard)
board:
  image: ""
  hostname: "puppetboard"
  url: ""

  resources:
    maxcpu: "2"
    maxram: "2Gi"
    mincpu: "200m"
    minram: "500Mi"