apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      hostname: {{ .Values.board.oauth2Proxy.hostname | quote }}

      containers:
      - image: {{ .Values.board.oauth2Proxy.image }}
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

        args:
        - --provider=oidc
        - --oidc-issuer-url={{ .Values.board.oauth2Proxy.oidcUrl }}
        - --code-challenge-method=plain
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180

        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: {{ .Values.board.oauth2Proxy.clientId }}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: {{ .Values.board.oauth2Proxy.clientSecret }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: {{ .Values.board.oauth2Proxy.cookieSecret }}

        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
