apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oauth2-proxy-np
spec:
  podSelector:
    matchLabels:
      app: oauth2-proxy
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports: # expose this Oauth2-proxy
    - protocol: TCP
      port: 4180
  egress:
  - ports: # to PuppetBoard
    - protocol: TCP
      port: 8080
  - ports: # to DNS
    - protocol: UDP
      port: 53
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
