apiVersion: v2
name: puppetserver
version: 0.1
appVersion: "8.0.10"
description: A Helm chart to deploy Puppet Master (puppetserver) in Kubernetes
icon: file://logo.png
keywords:
- puppet
- puppetmaster
- puppetserver
type: application
