instance:
  maxcpu: "1"
  maxram: "2Gi"
  mincpu: "500m"
  minram: "1Gi"

namespace: "puppet-ns"

server:
  image: "hub.cerit.io/josef_handl/puppetserver:mk2"
  hostname: "puppetserver"

db:
  image: "hub.cerit.io/josef_handl/puppetdb:mk1"
  hostname: "puppetdb"
