instance:
  keepCerts: true

namespace: ""

# Puppet Server application
server:
  image: "hub.cerit.io/josef_handl/puppetserver:mk2"
  hostname: "puppetserver"

  resources:
    maxcpu: "2"
    maxram: "5Gi"
    mincpu: "200m"
    minram: "3Gi"

# Puppet DB application
db:
  image: "hub.cerit.io/josef_handl/puppetdb:mk1"
  hostname: "puppetdb"

  resources:
    maxcpu: "2"
    maxram: "2Gi"
    mincpu: "200m"
    minram: "1Gi"

# CloudNativePG (PostgreSQL)
cnpg:
  database: "puppetdb"
  superuserpassword: "postgres"
  username: "puppetdb"
  password: "postgres"

  resources:
    maxcpu: "2"
    maxram: "2Gi"
    mincpu: "200m"
    minram: "500Mi"